In [1]:
import pandas as pd

In [3]:
starCatalog = pd.read_csv('../dataset/hygdata_v3.csv.zip',\
                          index_col='id', compression='zip')

In [4]:
starCatalog.fillna({'con': ''}, inplace=True)

,hip,hd,hr,gl,bf,proper,ra,dec,dist,pmra,...,bayer,flam,con,comp,comp_primary,base,lum,var,var_min,var_max
id,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,Sol,0.000000,0.000000,0.0000,0.00,...,NaN,NaN,,1,0,NaN,1.000000,NaN,NaN,NaN
1,1.0,224700.0,NaN,NaN,NaN,NaN,0.000060,1.089009,219.7802,-5.20,...,NaN,NaN,,1,1,NaN,9.638290,NaN,NaN,NaN
2,2.0,224690.0,NaN,NaN,NaN,NaN,0.000283,-19.498840,47.9616,181.21,...,NaN,NaN,,1,2,NaN,0.392283,NaN,NaN,NaN
3,3.0,224699.0,NaN,NaN,NaN,NaN,0.000335,38.859279,442.4779,5.24,...,NaN,NaN,,1,3,NaN,386.901132,NaN,NaN,NaN
4,4.0,224707.0,NaN,NaN,NaN,NaN,0.000569,-51.893546,134.2282,62.85,...,NaN,NaN,,1,4,NaN,9.366989,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119611,NaN,NaN,NaN,NN 4381,NaN,NaN,23.963895,38.629391,16.9492,-162.63,...,NaN,NaN,,1,119611,NaN,0.002200,NaN,NaN,NaN
119612,NaN,NaN,NaN,NN 4385,NaN,NaN,23.996567,47.762093,16.7224,864.68,...,NaN,NaN,,1,119612,NaN,0.000088,NaN,NaN,NaN
119613,NaN,NaN,NaN,NN 4386,NaN,NaN,23.996218,-44.067905,18.5185,-18.83,...,NaN,NaN,,1,119613,NaN,0.002224,NaN,NaN,NaN
119614,NaN,NaN,NaN,NN 4387,NaN,NaN,23.997386,-34.111986,12.8205,715.88,...,NaN,NaN,,1,119614,NaN,0.001086,NaN,NaN,NaN
119615,NaN,NaN,NaN,Gl 915,NaN,NaN,0.036059,-43.165974,7.8003,612.44,...,NaN,NaN,,1,119615,NaN,0.000319,NaN,NaN,NaN

In [5]:
# if a star's record shows it is in constellation Ursa Major AND that it has a proper name...
mask = (starCatalog['con'].str.contains('UMa'))\
     & (starCatalog['proper'].notna())

In [6]:
# then display it in a mini-table with columns 'proper', 'con', 'x', 'y', 'z' from the starCatalog
starCatalog[mask][['proper', 'con', 'x', 'y', 'z']]

                 proper  con          x         y          z
id
53754             Merak  UMa -13.103033  3.398358  20.360601
53905             Dubhe  UMa -17.298705  4.334880  33.191332
57767  Groombridge 1830  UMa  -7.187679  0.220247   5.561623
57828              Phad  UMa -15.094867  0.406425  20.552678
59592            Megrez  UMa -13.402309 -0.903455  20.710384
62757            Alioth  UMa -13.775959 -3.309169  20.972944
65173             Mizar  UMa -14.115808 -5.413302  21.531272
65272             Alcor  UMa -13.393436 -5.223608  20.521915
67088            Alkaid  UMa -18.529548 -9.394541  24.164506